"""add email_confirmations

Revision ID: 10a07c64dfce
Revises: 2c2b5ddd2d8d
Create Date: 2026-08-26 06:21:34.317248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a07c64dfce'
down_revision: Union[str, Sequence[str], None] = '2c2b5ddd2d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    A table rather than two columns on users, because a resend issues a new token
    without invalidating the old one. Columns would overwrite the token of the mail
    the user may already have open, and the older link would stop working with
    nothing to explain why.

    No backfill: existing users either confirmed already, in which case they need no
    token, or they never can, since nothing before this migration ever wrote
    email_confirmed_at. The resend endpoint is what gets them a token.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_confirmations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_email_confirmations_user_id'), 'email_confirmations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_confirmations_user_id'), table_name='email_confirmations')
    op.drop_table('email_confirmations')
    # ### end Alembic commands ###
