"""add invoices and invoice_lines

Revision ID: 3610e7b47b8a
Revises: 7c41ab90d5e2
Create Date: 2026-08-27 11:10:12.265727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Los cinco tipos enum ya existen en la base: los crearon las tablas anteriores, y
# `vouchertype` sobrevivio a 3d9a71e0c4b2, que tiro la columna de invoice_templates pero
# dejo el tipo a proposito porque sigue siendo el vocabulario de ARCA. Sin create_type=False
# esta migracion intenta crearlos de nuevo y corta con "type already exists".
def _enum(name, *labels):
    return postgresql.ENUM(*labels, name=name, create_type=False)


# revision identifiers, used by Alembic.
revision: str = '3610e7b47b8a'
down_revision: Union[str, Sequence[str], None] = '7c41ab90d5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Invoices are emitted facts, not editable documents, and the schema says so in three
    places. voucher_type is a stored column here while invoice_templates derives it, because
    the letter was fixed by ARCA on the day of emission and recomputing it later would
    rewrite a voucher that already exists at the tax authority. The totals are stored for the
    same reason: the CAE covers those numbers, so a future change to rounding must not move
    them. And the issuer and customer are copied field by field rather than only referenced,
    so that a customer correcting their address does not retroactively alter every PDF
    already sent to them.

    Neither foreign key to fiscal_identities or customers takes an ondelete, so the default
    NO ACTION refuses to delete a party that has invoices. template_id does take SET NULL:
    the template is provenance, not a dependency, and last year's model has to stay
    deletable.

    The unique constraint on (fiscal_identity_id, pos, voucher_type, number) mirrors the
    invariant ARCA enforces on its side. It is the backstop for the advisory lock in
    crud/invoice.py: if both were to fail, a duplicated invoice becomes an error instead of a
    row.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fiscal_identity_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('voucher_type', _enum('vouchertype', 'A', 'B', 'C', 'NCA', 'NCB', 'NCC'), nullable=False),
    sa.Column('pos', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('concepto', _enum('concepto', 'products', 'services', 'both'), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('cae', sa.String(length=14), nullable=False),
    sa.Column('cae_expiry', sa.Date(), nullable=False),
    sa.Column('net_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('iva_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('issuer_name', sa.String(length=150), nullable=False),
    sa.Column('issuer_tax_id', sa.String(length=11), nullable=False),
    sa.Column('issuer_condicion_iva', _enum('condicioniva', 'INSCRIPTO', 'EXENTO', 'FINAL', 'MONOTRIBUTO'), nullable=False),
    sa.Column('issuer_address', sa.String(length=200), nullable=True),
    sa.Column('issuer_iibb', sa.String(length=50), nullable=True),
    sa.Column('issuer_start_date', sa.Date(), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('customer_doc_type', _enum('doctype', 'CUIT', 'CUIL', 'DNI'), nullable=False),
    sa.Column('customer_doc_number', sa.String(length=11), nullable=False),
    sa.Column('customer_condicion_iva', _enum('condicioniva', 'INSCRIPTO', 'EXENTO', 'FINAL', 'MONOTRIBUTO'), nullable=False),
    sa.Column('customer_address', sa.String(length=200), nullable=True),
    sa.Column('customer_email', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['fiscal_identity_id'], ['fiscal_identities.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['invoice_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_identity_id', 'pos', 'voucher_type', 'number', name='uq_invoices_fiscal_identity_id_pos_voucher_type_number')
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_fiscal_identity_id'), 'invoices', ['fiscal_identity_id'], unique=False)
    op.create_index(op.f('ix_invoices_template_id'), 'invoices', ['template_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('iva_aliquot', _enum('ivaaliquot', 'exempt', 'reduced', 'standard', 'higher'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_invoices_template_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_fiscal_identity_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
