"""index foreign keys

Revision ID: 40c6538fece7
Revises: 5b6336135601
Create Date: 2026-08-08 23:32:14.369249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c6538fece7'
down_revision: Union[str, Sequence[str], None] = '5b6336135601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_invoice_template_lines_template_id'), 'invoice_template_lines', ['template_id'], unique=False)
    op.create_index(op.f('ix_invoice_templates_customer_id'), 'invoice_templates', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoice_templates_fiscal_identity_id'), 'invoice_templates', ['fiscal_identity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_templates_fiscal_identity_id'), table_name='invoice_templates')
    op.drop_index(op.f('ix_invoice_templates_customer_id'), table_name='invoice_templates')
    op.drop_index(op.f('ix_invoice_template_lines_template_id'), table_name='invoice_template_lines')
    # ### end Alembic commands ###
