"""add users and user_sessions

Revision ID: 45cbc9ddbf95
Revises: cf79c4f7610c
Create Date: 2026-08-18 18:55:30.620155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45cbc9ddbf95'
down_revision: Union[str, Sequence[str], None] = 'cf79c4f7610c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Identity only: no ownership columns yet. Scoping fiscal_identities and customers
    to a user is a separate unit, and adding those FKs here would create rows nobody
    owns for as long as it takes to write the queries that respect them.

    Two column choices are not self-evident from the DDL:

    `users.hashed_password` is String(255) because pwdlib writes an argon2id PHC
    string — about 97 characters today, and its length moves with the argon2
    parameters. The 72 that bcrypt suggests is a limit on the *input password*, not
    on any hash.

    `user_sessions.token_hash` is String(64) because it holds a SHA-256 hexdigest,
    not an argon2 hash. The token is 256 bits from `secrets`, so there is no
    dictionary to attack and a slow KDF would buy nothing while costing ~100ms on
    every authenticated request. Its unique constraint is also the index that every
    such request looks the token up by.

    The FK cascades so sessions die with their user; the model pairs that with
    passive_deletes=True so Postgres does it in one statement.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Drops both tables and every account in them. Safe while the only users are
    development ones; from the first real registration this is a data-loss step.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
