"""add invoices.sent_at

Revision ID: 49023933c5a4
Revises: 3610e7b47b8a
Create Date: 2026-08-27 11:36:03.572639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49023933c5a4'
down_revision: Union[str, Sequence[str], None] = '3610e7b47b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    When the invoice was last emailed to the customer, or NULL if it never was. Nullable with
    no backfill and no default: rows that predate this column were genuinely never sent, so
    NULL is the truth rather than a gap.

    A timestamp rather than a boolean, like email_confirmed_at and delegation_verified_at
    before it — the "when" is the part anyone asks about. Resending overwrites it instead of
    appending: the question the screen answers is "has this gone out?", and a resend history
    would be a table for a question nobody asks.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'sent_at')
    # ### end Alembic commands ###
