"""initial schema

Revision ID: 5b6336135601
Revises: 
Create Date: 2026-08-08 23:14:54.213653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6336135601'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('condicion_iva', sa.Enum('INSCRIPTO', 'EXENTO', 'FINAL', 'MONOTRIBUTO', name='condicioniva'), nullable=False),
    sa.Column('doc_type', sa.Enum('CUIT', 'CUIL', 'DNI', 'FINAL', name='doctype'), nullable=False),
    sa.Column('tax_id', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscal_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('condicion_iva', sa.Enum('INSCRIPTO', 'EXENTO', 'FINAL', 'MONOTRIBUTO', name='condicioniva'), nullable=False),
    sa.Column('tax_id', sa.String(length=11), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('iibb', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_table('invoice_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('fiscal_identity_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('voucher_type', sa.Enum('A', 'B', 'C', 'NCA', 'NCB', 'NCC', name='vouchertype'), nullable=False),
    sa.Column('pos', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.Enum('products', 'services', 'both', name='concepto'), server_default='products', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['fiscal_identity_id'], ['fiscal_identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_template_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('iva_aliquot', sa.Enum('exempt', 'reduced', 'standard', 'higher', name='ivaaliquot'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['invoice_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_template_lines')
    op.drop_table('invoice_templates')
    op.drop_table('fiscal_identities')
    op.drop_table('customers')
    # ### end Alembic commands ###

    # Autogenerate no revierte los tipos ENUM de PostgreSQL: CREATE TYPE crea un
    # objeto de esquema, no de tabla, y DROP TABLE no lo toca. Sin esto, un
    # downgrade seguido de upgrade falla con "type already exists".
    bind = op.get_bind()
    for enum_name in ('condicioniva', 'doctype', 'vouchertype', 'concepto', 'ivaaliquot'):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
