"""unique invoice template name per fiscal identity

Revision ID: ca13b855923c
Revises: a1f4c9d27b83
Create Date: 2026-08-15 13:44:26.059902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca13b855923c'
down_revision: Union[str, Sequence[str], None] = 'a1f4c9d27b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_invoice_templates_fiscal_identity_id_name', 'invoice_templates', ['fiscal_identity_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoice_templates_fiscal_identity_id_name', 'invoice_templates', type_='unique')
    # ### end Alembic commands ###
